'use client';
import { useEffect, useState, type Dispatch, type SetStateAction } from 'react';
import { Button, Card, Input, Textarea } from '@/components/ui';
import { DataTable, KPIBox, StatusBadge } from '@/components/common';
import { api, API } from '@/lib/api';
import type { AllocationHistoryEntry, AllocationResult, DailyInput, EmployeeResolutionResponse, OperationalRate, RoleCatalogItem, RolePlan, RolePlanItem, RolePlanValidation, ValidationResult, VolumeParseResponse } from '@/lib/types';
const sampleIds='123456001\n123456002\n123456003\n123456004\n123456005\n123456006\n123456007\n123456008\n123456009\n123456010\n123456011\n123456012\n123456013\n123456014\n123456015\n123456016\n123456001\n999999999';
const sampleSd='C5\t442\t2 \t12 \t55 \t371 \t18\t18\t0\t0\t96.87%\t0\t-\nC6\t619\t1 \t20 \t62 \t508 \t24\t25\t0\t18\t96.21%\t1\t0';
const sampleNd='C5 100\nC6 150';
const typeLabels:Record<string,string>={volume_based:'Volumenabhängig',mandatory:'Pflichtrolle',optional:'Optional',fixed:'Fix',surplus:'Überhang'};
const formatType=(t:string)=>typeLabels[t]??t;
const utilization=(i:RolePlanItem)=>i.average_utilization_percent==null?'—':`${Math.round(i.average_utilization_percent)} %`;
function recalcPlan(rp:RolePlan){const stow=rp.items.find(i=>i.engine_cluster==='Stow A'); const items=rp.items.map(i=>i.engine_cluster==='Pick A'&&stow?{...i,current_count:stow.current_count,suggested_count:stow.current_count,editable:false,warnings:Array.from(new Set([...i.warnings,'Automatisch gekoppelt an Stow A']))}:i); return {...rp,items,current_positions:items.reduce((sum,it)=>sum+it.current_count,0)}}
export default function Home(){
 const [shiftDate,setShiftDate]=useState('2026-07-10'); const [rawIds,setRawIds]=useState(sampleIds); const [emp,setEmp]=useState<EmployeeResolutionResponse|null>(null);
 const [sd,setSd]=useState(sampleSd); const [nd,setNd]=useState(sampleNd); const [vol,setVol]=useState<VolumeParseResponse|null>(null); const [rates,setRates]=useState<OperationalRate[]>([]);
 const [activeTab,setActiveTab]=useState<'new'|'history'|'rates'>('new');
 const [validation,setValidation]=useState<ValidationResult|null>(null); const [rolePlan,setRolePlan]=useState<RolePlan|null>(null); const [catalog,setCatalog]=useState<RoleCatalogItem[]>([]); const [addOpen,setAddOpen]=useState(false); const [addRole,setAddRole]=useState(''); const [addCount,setAddCount]=useState(1); const [addError,setAddError]=useState(''); const [roleVal,setRoleVal]=useState<RolePlanValidation|null>(null); const [alloc,setAlloc]=useState<AllocationResult|null>(null); const [finalFile,setFinalFile]=useState(''); const [history,setHistory]=useState<AllocationHistoryEntry[]>([]); const [error,setError]=useState(''); const [loading,setLoading]=useState(''); const [details,setDetails]=useState(false);
 useEffect(()=>{api<OperationalRate[]>('/config/rates').then(setRates).catch(e=>setError(e.message)); api<RoleCatalogItem[]>('/role-plan/catalog').then(setCatalog).catch(()=>{}); loadHistory()},[]);
 const daily:DailyInput={shift_date:shiftDate,employees:emp?.employees??[],volumes:vol?.aisles??[],rates,previous_day_found:true};
 const canFinal=roleVal?.is_valid && rolePlan;
 async function run<T>(label:string,fn:()=>Promise<T>){setError('');setLoading(label);try{return await fn()}catch(e){setError(e instanceof Error?e.message:'Unbekannter Fehler')}finally{setLoading('')}}
 const loadHistory=()=>api<AllocationHistoryEntry[]>('/allocations').then(setHistory).catch(()=>{});
 const resolve=()=>run('Mitarbeiter werden erkannt',async()=>setEmp(await api('/employees/resolve',{method:'POST',body:JSON.stringify({raw_employee_ids:rawIds})})));
 const parseVol=()=>run('Volumen werden geparst',async()=>setVol(await api('/volumes/parse',{method:'POST',body:JSON.stringify({sd_raw_text:sd,nd_raw_text:nd})})));
 const validate=()=>run('Validierung läuft',async()=>setValidation(await api('/validation/pre-run',{method:'POST',body:JSON.stringify(daily)})));
 const calcRole=()=>run('Rollenbedarf wird berechnet',async()=>{const rp=await api<RolePlan>('/role-plan/calculate',{method:'POST',body:JSON.stringify(daily)});setRolePlan(rp);setRoleVal(await api('/role-plan/validate',{method:'POST',body:JSON.stringify(rp)}))});
 async function validateAndSet(rp:RolePlan){setRolePlan(rp); setRoleVal(await api('/role-plan/validate',{method:'POST',body:JSON.stringify(rp)}));}
 async function updateRole(i:number,n:number){if(!rolePlan)return; if(n<0){setError('Rollenanzahl darf nicht kleiner als 0 sein.');return} const changed={...rolePlan,items:rolePlan.items.map((it,idx)=>idx===i?{...it,current_count:n,average_utilization_percent:it.engine_cluster.startsWith('Stow')&&n>0&&it.average_utilization_percent!=null?Math.round((it.average_utilization_percent*it.current_count/n)*10)/10:it.average_utilization_percent}:it)}; await validateAndSet(recalcPlan(changed));}
 async function addRoleToPlan(){if(!rolePlan)return; setAddError(''); const cfg=catalog.find(c=>c.engine_cluster===addRole); if(!cfg){setAddError('Bitte eine bekannte Rolle auswählen.');return} if(rolePlan.items.some(i=>i.engine_cluster===cfg.engine_cluster)){setAddError('Diese Rolle ist bereits im Rollenplan enthalten.');return} if(addCount<0){setAddError('Rollenanzahl darf nicht kleiner als 0 sein.');return} const item:RolePlanItem={engine_cluster:cfg.engine_cluster,suggested_count:0,current_count:addCount,minimum_count:cfg.minimum,maximum_count:undefined,mandatory:cfg.type==='mandatory',editable:cfg.editable,type:cfg.type,available_skilled_employees:999,warnings:[],average_utilization_percent:null}; await validateAndSet(recalcPlan({...rolePlan,items:[...rolePlan.items,item]})); setAddOpen(false); setAddRole(''); setAddCount(1);}
 const availableRoles=catalog.filter(c=>rolePlan&&!rolePlan.items.some(i=>i.engine_cluster===c.engine_cluster));
 const finalAlloc=()=>run('Finale Allocation',async()=>setAlloc(await api('/allocation/final',{method:'POST',body:JSON.stringify({daily_input:daily,role_plan:rolePlan})})));
 const finalize=()=>run('Finalisierung',async()=>{const res=await api<{export_filename:string}>('/allocation/finalize',{method:'POST',body:JSON.stringify({daily_input:daily,role_plan:rolePlan,allocation_result:alloc})});setFinalFile(res.export_filename); await loadHistory();});
 return <main className="mx-auto max-w-7xl space-y-6 p-6 text-slate-100"><section className="rounded-3xl border border-slate-800 bg-slate-950 p-6 shadow-2xl shadow-black/30"><h1 className="text-4xl font-bold text-white">Amazon - Job Allocation Engine</h1></section><nav className="flex flex-wrap gap-3">{([['new','Neue Allocation'],['history','Historie'],['rates','Rates & Parameter']] as const).map(([key,label])=><button key={key} onClick={()=>setActiveTab(key)} className={`rounded-xl border px-4 py-2 font-semibold transition ${activeTab===key?'border-brand bg-brand text-slate-950':'border-slate-800 bg-slate-900 text-slate-300 hover:border-brand/70 hover:text-white'}`}>{label}</button>)}</nav>{error&&<Card className="border-red-500/40 bg-red-950/40"><b>Fehler:</b> {error}</Card>}{loading&&<Card className="border-brand/40 bg-brand/10">{loading} …</Card>}
 {activeTab==='new'&&<>
 <Card><h2 className="text-xl font-semibold">1. Schicht</h2><div className="mt-4 grid gap-4 md:grid-cols-3"><label>Schichtdatum<Input type="date" value={shiftDate} onChange={e=>setShiftDate(e.target.value)}/></label><KPIBox label="Vortagsdaten" value="✓ gefunden"/><KPIBox label="Frühere finale Allocation" value="28 Zuweisungen"/></div></Card>
 <Card><h2 className="text-xl font-semibold">2. Mitarbeiter</h2><Textarea rows={7} value={rawIds} onChange={e=>setRawIds(e.target.value)} /><Button className="mt-3" onClick={resolve}>Mitarbeiter erkennen</Button>{emp&&<><div className="mt-4 grid gap-3 md:grid-cols-4"><KPIBox label="IDs erkannt" value={emp.total_ids}/><KPIBox label="Gefunden" value={emp.found_count}/><KPIBox label="Unbekannt" value={emp.unknown_ids.length}/><KPIBox label="Duplikate" value={emp.duplicate_ids.length}/></div><DataTable><thead><tr><th>Status</th><th>Employee ID</th><th>Name</th><th>Badge</th><th>User</th><th>Hinweise</th><th>New Hire</th><th>L3</th><th>Anwesend</th></tr></thead><tbody>{emp.employees.map(e=><tr className="border-t border-slate-800" key={e.employee_id}><td><StatusBadge type={e.status==='found'?'success':'warning'}>{e.status}</StatusBadge></td><td>{e.employee_id}</td><td>{e.name}</td><td>{e.badge_id}</td><td>{e.user_id}</td><td>{e.notes.join(', ')}</td><td>{e.new_hire?'Ja':'Nein'}</td><td>{e.l3?'Ja':'Nein'}</td><td>{e.present?'Ja':'Nein'}</td></tr>)}</tbody></DataTable></>}</Card>
 <Card><h2 className="text-xl font-semibold">3. Volumen</h2><div className="grid gap-4 md:grid-cols-2"><label>SD-Volumendaten einfügen<Textarea rows={7} value={sd} onChange={e=>setSd(e.target.value)}/></label><label>ND-Volumendaten einfügen<Textarea rows={7} value={nd} onChange={e=>setNd(e.target.value)}/></label></div><Button className="mt-3" onClick={parseVol}>Volumen parsen</Button>{vol&&<><div className="mt-4 grid gap-3 md:grid-cols-5"><KPIBox label="SD" value={vol.sd_total}/><KPIBox label="ND" value={vol.nd_total}/><KPIBox label="Total" value={vol.total_volume}/><KPIBox label="Aisles" value={vol.aisle_count}/><KPIBox label="Finger" value={vol.active_fingers.join(', ')}/></div><DataTable><thead><tr><th>Finger</th><th>Aisle</th><th>SD Volume</th><th>ND Volume</th><th>Total</th></tr></thead><tbody>{vol.aisles.map(a=><tr className="border-t border-slate-800" key={a.aisle}><td>{a.finger}</td><td>{a.aisle}</td><td>{a.sd_volume}</td><td>{a.nd_volume}</td><td>{a.total_volume}</td></tr>)}</tbody></DataTable>{vol.warnings.length>0&&<div className="mt-3 space-y-1 text-sm text-amber-300">{vol.warnings.map((w,idx)=><p key={idx}>⚠ {w}</p>)}</div>}</>}</Card>
 <Card><h2 className="text-xl font-semibold">4. Validierung</h2><Button onClick={validate}>Eingaben validieren</Button>{validation&&<div className="mt-4 space-y-2">{validation.issues.map((i,idx)=><p key={idx}><StatusBadge type={i.severity==='error'?'error':i.severity==='warning'?'warning':i.severity==='success'?'success':'info'}>{i.severity}</StatusBadge> <span className="ml-2">{i.message}</span></p>)}<b>{validation.error_count} Fehler, {validation.warning_count} Hinweise</b></div>}</Card>
 <Card><h2 className="text-xl font-semibold">5. Rollenplan</h2><Button disabled={validation?.is_valid===false} onClick={calcRole}>Rollenbedarf berechnen</Button>{rolePlan&&<><div className="my-3"><b>Soll: {rolePlan.target_positions} Positionen · Aktuell: {roleVal?.current_positions}</b> {roleVal?.is_valid?<StatusBadge type="success">Summe korrekt</StatusBadge>:<StatusBadge type="error">ungültig</StatusBadge>}</div><DataTable><thead><tr><th>Engine Cluster</th><th>Vorgeschlagen</th><th>Aktuell</th><th>Typ</th><th>Ø Auslastung</th><th>Skilled</th><th>Warnungen</th></tr></thead><tbody>{rolePlan.items.map((i,idx)=><tr className="border-t border-slate-800" key={i.engine_cluster}><td>{i.engine_cluster}</td><td>{i.suggested_count}</td><td><Input disabled={!i.editable || i.engine_cluster==='Pick A'} min={0} type="number" value={i.current_count} onChange={e=>updateRole(idx,Number(e.target.value))}/>{i.engine_cluster==='Pick A'&&<p className="mt-1 text-xs text-brand">Automatisch gekoppelt an Stow A</p>}</td><td>{formatType(i.type)}</td><td>{utilization(i)}</td><td>{i.available_skilled_employees}</td><td>{i.warnings.join(', ')}</td></tr>)}</tbody></DataTable><Button className="mt-3" onClick={()=>{setAddOpen(true);setAddRole(availableRoles[0]?.engine_cluster??'')}}>+ Rolle hinzufügen</Button>{addOpen&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><div className="w-full max-w-md rounded-2xl border border-slate-700 bg-slate-950 p-6 shadow-2xl"><h3 className="text-xl font-semibold text-white">Rolle hinzufügen</h3><label className="mt-4 block">Rolle<select className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-900 px-3 py-2 text-slate-100" value={addRole} onChange={e=>setAddRole(e.target.value)}>{availableRoles.map(r=><option key={r.engine_cluster} value={r.engine_cluster}>{r.role} · {r.engine_cluster} · {formatType(r.type)}</option>)}</select></label><label className="mt-4 block">Anzahl<Input min={0} type="number" value={addCount} onChange={e=>setAddCount(Number(e.target.value))}/></label>{addError&&<p className="mt-3 text-red-300">✕ {addError}</p>}<div className="mt-5 flex justify-end gap-3"><Button className="bg-slate-800 text-slate-100 hover:bg-slate-700" onClick={()=>setAddOpen(false)}>Abbrechen</Button><Button onClick={addRoleToPlan}>Hinzufügen</Button></div></div></div>}{roleVal?.issues.map((i,idx)=><p className="mt-2 text-red-300" key={idx}>✕ {i.message}</p>)}</>}</Card>
 <Card><h2 className="text-xl font-semibold">6. Finale Allocation</h2><Button disabled={!canFinal} onClick={finalAlloc}>Finale Allocation berechnen</Button>{alloc&&<><div className="mt-4 grid gap-3 md:grid-cols-5">{Object.entries(alloc.kpis).map(([k,v])=><KPIBox key={k} label={k} value={v}/>)}</div><Button className="my-3 bg-slate-800 text-slate-100 hover:bg-slate-700" onClick={()=>setDetails(!details)}>Details anzeigen</Button><DataTable><thead><tr><th>Employee ID</th><th>Badge</th><th>Name</th><th>User</th><th>Rolle</th>{details&&<><th>Engine Cluster</th><th>FCLM</th></>}<th>Finger</th><th>Aisles</th><th>Volume</th><th>Load %</th><th>Status</th></tr></thead><tbody>{alloc.assignments.map(a=><tr className="border-t border-slate-800" key={a.employee_id}><td>{a.employee_id}</td><td>{a.badge_id}</td><td>{a.name}</td><td>{a.user_id}</td><td>{a.role}</td>{details&&<><td>{a.engine_cluster}</td><td>{a.fclm_cluster}</td></>}<td>{a.finger}</td><td>{a.primary_aisles.join(', ')}</td><td>{a.primary_volume}</td><td>{a.load_percent}</td><td>{a.status}</td></tr>)}</tbody></DataTable><p className="mt-3"><b>Warnungen:</b> {alloc.warnings.join(', ')||'Keine'}</p><p><b>Standby:</b> {alloc.standby_employees.map(e=>e.name).join(', ')||'Keine'}</p></>}</Card>
 <Card><h2 className="text-xl font-semibold">7. Finalisieren & Export</h2><Button disabled={!alloc} onClick={finalize}>Allocation finalisieren</Button>{finalFile&&<p className="mt-3"><StatusBadge type="success">Allocation erfolgreich finalisiert</StatusBadge> <a className="ml-3 font-semibold text-brand" href={`${API}/exports/${encodeURIComponent(finalFile)}`}>Excel herunterladen</a></p>}</Card></>}{activeTab==='history'&&<HistoryView history={history}/>} {activeTab==='rates'&&<RatesView rates={rates} setRates={setRates}/>}</main>}
function HistoryView({history}:{history:AllocationHistoryEntry[]}){return <Card><h2 className="text-xl font-semibold">Historie</h2>{history.length===0?<p className="mt-3 text-slate-400">Noch keine finalisierte Allocation.</p>:<DataTable><thead><tr><th>Datum</th><th>Run-ID</th><th>Status</th><th>Zugewiesen</th><th>Gesamtvolumen</th><th>Export-Datei</th></tr></thead><tbody>{history.map(h=><tr className="border-t border-slate-800" key={h.run_id}><td>{h.shift_date}</td><td>{h.run_id}</td><td>{h.status}</td><td>{h.assigned_count}</td><td>{h.total_volume}</td><td><a className="text-brand" href={`${API}/exports/${encodeURIComponent(h.export_filename)}`}>{h.export_filename}</a></td></tr>)}</tbody></DataTable>}</Card>}
function formatValue(rate:OperationalRate){return rate.step===0.25?Number(rate.current_value).toFixed(2):String(rate.current_value)}
function RatesView({rates,setRates}:{rates:OperationalRate[];setRates:Dispatch<SetStateAction<OperationalRate[]>>}){
 const update=(i:number,value:string)=>setRates(rs=>rs.map((x,ix)=>ix===i?{...x,current_value:x.step===0.25?Math.round(Number(value)*4)/4:Number(value)}:x));
 return <Card><h2 className="text-xl font-semibold">Rates & Parameter</h2><p className="mt-2 text-sm text-slate-400">Aktuelle Werte werden im Daily-Allocation-Flow automatisch verwendet. Standardwerte bleiben unverändert.</p><DataTable><thead><tr><th>Parametername</th><th>Standardwert</th><th>Aktueller Wert</th><th>Einheit</th></tr></thead><tbody>{rates.map((r,i)=><tr className="border-t border-slate-800" key={r.key}><td>{r.label}</td><td>{r.step===0.25?Number(r.default_value).toFixed(2):r.default_value}</td><td><Input type="number" step={r.step??1} value={formatValue(r)} onChange={e=>update(i,e.target.value)}/></td><td>{r.unit}</td></tr>)}</tbody></DataTable></Card>
}
